### ISSUE TITLE
Informações Necessárias

### ISSUE THREAD

**Issue by uira** [ForaDoEixo/TVNINJA#1]
- **_id:** un id unico, si no hay lo genero

- **image:** una imagen del contenido (se puede generar, pero es mejor si esta curado)

- **cover:** el cover

- **torrent:** un link al recurso online, ni no hay lo genero

- **title:** el titulo

- **genre:** generos

- **synopsis:** una descripcion

- **runtime:** tiempo, si no hay lo genero

- **year:** año de produccion

- **health:** esto es un indicador de la salud del recurso, si no hay lo genero.

- **subtitle:** subtitulo (puede no estar)

- **backdrop:** imagen de fondo

- **rating:** un valor de qualidad de usuario

- **trailer:** link a un trailer en youtube (puede no estar)

**Comment by xaiki** [comment]
https://github.com/butterproviders/butter-provider/blob/master/README.md

**Comment by xaiki** [comment]
fixed in gdocs
